### ISSUE TITLE
Introducción a Spring Boot con Thymeleaf

### ISSUE THREAD

**Issue by josdem** [gdljug/propuestas-techtalks#1]
**Descripción**

Mostraré como poder crear un proyecto Spring Boot desde cero, y como poder agregar fácilmente un template engine como Thymeleaf

**Biografía**

José Luis De la Cruz Morales
Softtek
Desarrollando software backend, frontend y standalone principalmente usando Spring Framework.

**Comment by agbsys** [comment]
me parece interesante el tema con gusto me apunto para asistir, aun que veo esta publicado desde Mayo, todavia esta en pie la propuesta

**Comment by gabriel-fatih** [comment]
Sounds great, count me in!

**Comment by heryxpc** [comment]
Si, la propuesta aún está en pie. No olviden votarla dando click en el +.
