### ISSUE TITLE
Spring Boot Workshop

### ISSUE THREAD

**Issue by josdem** [gdljug/propuestas-techtalks#10]
**Descripción**

Mostraré en un taller lo siguiente de Spring Boot:

- Creando un proyecto MVC con Spring Boot
- Incorporación de Spring Data JPA
- Validación de modelo con Hibernate Validator
- Incorporación de Thymeleaf
- Incorporación de Bootstrap

**Biografía**

José Luis De la Cruz Morales
Softtek
Desarrollando software backend, frontend y standalone principalmente usando Spring Framework.

**Comment by gabriel-fatih** [comment]
¡Anotado!
