### ISSUE TITLE
A practical introduction to Scala

### ISSUE THREAD

**Issue by AlexITC** [gdljug/propuestas-techtalks#11]
### Descripción
Una introducción práctica a Scala, la idea es hablar sobre sus ventajas y desventajas, así como casos de éxito.

Temas a cubrir brevemente:
- Unified Types
- Strings
- Type Inference
- Higher Order Functions
- Currying
- Case Classes
- Algebraic Data Types
- Pattern Matching
- Error Handling
- Option
- Weak Types
- Strong Types

Una platica muy similar a: https://www.youtube.com/watch?v=y1gnsA6Owto

### Speaker
Alexis Hernández, Freelance trabajando para Samsung (Silicon Valley) a través de Blue Trail Software.

Todologo, desde sistemas embebidos a desarrollo móvil y web, experiencia principalmente diseñando y construyendo sistemas escalables teniendo en cuenta buenas prácticas y seguridad.

**Comment by chuucks** [comment]
Hola @AlexITC se ve muy interesandte para compartir con la comunidad una introducción a este lenguaje.

- Un comentario: la charlas en JUG duran en promedio 30 min y la charla que compartes es de 1 hora.
- Una pregunta: la charla la darías presencial, cierto?

Saludos y esperamos tus comentarios :)

**Comment by AlexITC** [comment]
Puedo reducirla a 30 minutos, y presencial.
