### ISSUE TITLE
Refactoring Mejorando el Diseño de Código Legado

### ISSUE THREAD

**Issue by josdem** [gdljug/propuestas-techtalks#14]
**Descripción**

Mostraré como poder trabajar con código legado para mejorar su diseño. Usaré TDD con Junit como método de pruebas y Java como lenguaje.

**Biografía**

José Luis De la Cruz Morales
Softtek
Desarrollando software backend, frontend y standalone principalmente usando Spring Framework.

**Comment by chuucks** [comment]
Justo ahora es lo que necesito. Las aplicaciónes Legacy pueden convertirse en un dolor de cabeza
