### ISSUE TITLE
Creating Telegram Bots

### ISSUE THREAD

**Issue by jsedano** [gdljug/propuestas-techtalks#18]
**Description**
Telegram is a messaging platform with 200 million monthly active users and it has support for making bots by exposing an easy to consume json API. We will use jsonschema2pojo to auto generate the objects we need, RestTemplate to make the call to the endpoint and everything will be glued with Spring. We will also run some easy use cases (like an echo bot). 

**About Me**
Juan Carlos Sedano is a Java Developer Senior at Luxoft. He loves to code, learning new stuff and improving his skills

**Comment by chuucks** [comment]
Gracias por tu propuesta Juan, te confirmamos la fecha del meetup

**Comment by chuucks** [comment]
cc @josdem @heryxpc
