### ISSUE TITLE
Como y Cuando Usar Patrones de Diseño

### ISSUE THREAD

**Issue by yobijoss** [gdljug/propuestas-techtalks#19]
Un patrón de diseño es un molde muy práctico para resolver problemas ya identificados en cualquier capa de nuestra aplicación. 

En esta charla exploraremos la definición junto con un ejemplo de 3 patrones de diseño ampliamente usados: 
- Strategy Pattern
- Composite Pattern
- Decorator Pattern

Jugaremos con ellos en 3 proyectos Android escritos en Java.

Pilón!
- También se expondrá el caso en el que un patrón puede perjudicar el diseño en vez de ayudar!

**Comment by chuucks** [comment]
Gracias @yobijoss por tu propuesta de charla para este mes. Te confirmamos en cuanto tengamos fecha y lugar. CC @heryxpc @chrisom79
