### ISSUE TITLE
Vert.x como herramienta para aplicaciones escalables

### ISSUE THREAD

**Issue by neodevelop** [gdljug/propuestas-techtalks#2]
A través de esta charla se pretende mostrar:

- Un modelo de concurrencia basado en actores implementado en Vertx.
- El uso de Vert.x para distribuir una aplicación en un cluster
- La creación de webapps de "tiempo real"
- El diseño de aplicaciones que crecen por sí solas

## Acerca de mí

**José Juan Reyes Zuñiga**
_MakingDevs_
He hecho algunas aplicaciones en varios contextos, principalmente bancos y educación, también promocioné algunas otras comunidades, fui podcaster y la JVM siempre me dió cosas buenas al final del día.

**Comment by chuucks** [comment]
Hola @neodevelop tenemos meetup este mes, estás disponible? Te enviamos correo...
