### ISSUE TITLE
Java code quality

### ISSUE THREAD

**Issue by skuarch** [gdljug/propuestas-techtalks#5]
En esta platica explicare como mantener la calidad del codigo para evitar malas practicas, se mostrara el uso **plugins** de maven y servidores que analizan el codigo para que todo se realice **automaticamente** y el programador se enfoque a realizar la escritura del codigo y el **code review** se delege a un proceso automatizado

- Introduccion a maven
- Estilo del codigo
- Analizadores estaticos de codigo
- Servidores para analizar el codigo 
- Integracion con jenkins

**Comment by skuarch** [comment]
vota usando la funcionalidad "Pick your reaction" en los comentarios del issue y selecciona un +1

**Comment by josdem** [comment]
Repositorio de la charla técnica: https://github.com/gdljug/java-code-quality
